# Generated by Django 4.1 on 2022-08-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'cuenta',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField(max_length=100)),
                ('employee_surname', models.TextField(max_length=100)),
                ('employee_hire_date', models.TextField(max_length=300)),
                ('employee_dni', models.TextField(max_length=100)),
                ('branch_id', models.IntegerField()),
                ('cd_adrress_id', models.IntegerField()),
            ],
            options={
                'db_table': 'employeed',
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('movimientos', models.TextField(max_length=100)),
                ('monto', models.IntegerField()),
                ('numero_cuenta', models.IntegerField()),
                ('tipo_operacion', models.TextField(max_length=200)),
                ('hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='TiposDeCuenta',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.TextField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
