# Generated by Django 4.1 on 2022-08-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('cd_card_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_num_card', models.IntegerField()),
                ('cd_cvv', models.IntegerField()),
                ('cd_date_issue', models.TextField(max_length=200)),
                ('cd_date_expiration', models.TextField(max_length=50)),
                ('cd_card_id', models.IntegerField()),
                ('cd_card_brand_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
