# Generated by Django 4.1 on 2022-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.TextField(max_length=40)),
                ('customer_surname', models.TextField(max_length=25)),
                ('customer_DNI', models.IntegerField()),
                ('customer_direccion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField(max_length=100)),
                ('cd_account_type_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.TextField(max_length=100)),
                ('employee_surname', models.TextField(max_length=100)),
                ('employee_hire_date', models.TextField(max_length=300)),
                ('employee_dni', models.TextField(max_length=100)),
                ('branch_id', models.IntegerField()),
                ('cd_adrress_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movimiento', models.IntegerField()),
                ('movimientos', models.TextField(max_length=100)),
                ('monto', models.IntegerField()),
                ('numero_cuenta', models.IntegerField()),
                ('tipo_operacion', models.TextField(max_length=200)),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('loan_type', models.TextField(max_length=200)),
                ('loan_date', models.TextField(max_length=500)),
                ('loan_total', models.IntegerField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_card_type_id', models.IntegerField()),
                ('cd_num_card', models.IntegerField()),
                ('cd_cvv', models.IntegerField()),
                ('cd_date_issue', models.TextField(max_length=200)),
                ('cd_date_expiration', models.TextField(max_length=50)),
                ('cd_card_id', models.IntegerField()),
                ('cd_card_brand_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
            ],
        ),
    ]
