# Generated by Django 4.1 on 2022-08-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_DNI', models.TextField(db_column='customer_DNI')),
                ('customer_direccion', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.DeleteModel(
            name='clientes',
        ),
        migrations.DeleteModel(
            name='cuenta',
        ),
        migrations.DeleteModel(
            name='empleado',
        ),
        migrations.DeleteModel(
            name='movimientos',
        ),
        migrations.DeleteModel(
            name='prestamos',
        ),
        migrations.DeleteModel(
            name='tarjetas',
        ),
    ]
